(evil-mode 1)
(projectile-mode 1)
(lsp-ui-mode 1)
(lsp-mode 1)
(vertico-mode 1)
(company-mode 1)
(rainbow-delimiters-mode 1)
(show-paren-mode 1)
(load-theme 'leuven)
(setq inferior-lisp-program "/nix/store/wjaraq6qygaabavbzr71idlif4g5bxwv-sbcl-2.1.11/bin/sbcl")
